version: '3.3'

services:

  web:
    container_name: kvartirka_web
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    env_file:
      - ./src/.env.docker
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./:/app

  db:
    container_name: kvartirka_db
    image: postgres:13-alpine
    restart: always
    volumes:
      - main_db:/var/lib/postgresql/data/
    env_file:
      - ./src/.env.docker
    ports:
      - 5432:5432

volumes:
  main_db: