version: '3'

services:

  postgres:
    image: postgres:13-alpine
    env_file:
      - ./src/.env.docker
    volumes:
      - kvartirka_single:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  kvartirka_single: