version: '3'

services:

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: kvartirka
      POSTGRES_USER: kvartirka
      POSTGRES_PASSWORD: kvartika
    volumes:
      - kvartirka_single:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  kvartirka_single: